// port-lint: source section/github.rs
package io.github.kotlinmania.coloreyre.section.github

import io.github.kotlinmania.coloreyre.Backtrace
import io.github.kotlinmania.coloreyre.Location
import io.github.kotlinmania.coloreyre.SpanTrace

internal data class IssueSection(
    private val url: String,
    private val msg: String,
    private val location: Location? = null,
    private val backtrace: Backtrace? = null,
    private val spanTrace: SpanTrace? = null,
    private val metadata: List<Pair<String, Any>> = emptyList(),
) {
    internal fun withLocation(location: Location?): IssueSection = copy(location = location)

    internal fun withBacktrace(backtrace: Backtrace?): IssueSection = copy(backtrace = backtrace)

    internal fun withSpanTrace(spanTrace: SpanTrace?): IssueSection = copy(spanTrace = spanTrace)

    internal fun withMetadata(metadata: List<Pair<String, Any>>): IssueSection = copy(metadata = metadata)

    override fun toString(): String {
        val locationMetadata = location?.let { listOf("location" to it as Any) } ?: emptyList()
        val metadataSection = MetadataSection(metadata + locationMetadata).toString()
        val body = Body()
        body.pushSection("Error", ConsoleSection(msg))

        if (metadata.isNotEmpty()) {
            body.pushSection("Metadata", metadataSection)
        }

        if (spanTrace != null) {
            body.pushSection("SpanTrace", Collapsed(ConsoleSection("SpanTrace:\n$spanTrace")))
        }

        if (backtrace != null) {
            body.pushSection("Backtrace", Collapsed(ConsoleSection("Backtrace:\n$backtrace")))
        }

        val issueUrl = Url.withParams(
            url,
            listOf("title" to "<autogenerated-issue>", "body" to body.body),
        ) ?: url
        return "Consider reporting this error using this URL: $issueUrl"
    }
}

private class Body {
    var body: String = ""
        private set

    fun pushSection(header: String, section: Any) {
        val separator = if (body.isEmpty()) "" else "\n\n"
        body += "$separator## $header\n$section"
    }
}

private data class MetadataSection(
    private val metadata: Iterable<Pair<String, Any>>,
) {
    override fun toString(): String = buildString {
        appendLine("|key|value|")
        appendLine("|--|--|")
        for ((key, value) in metadata) {
            appendLine("|**$key**|$value|")
        }
    }
}

private data class ConsoleSection<T>(
    private val value: T,
) {
    override fun toString(): String = "```\n$value\n```"
}

private data class Collapsed<T>(
    private val value: T,
) {
    override fun toString(): String = "\n<details>\n\n$value\n</details>"
}

private data class DisplayFromDebug<T>(
    private val value: T,
) {
    override fun toString(): String = value.toString()
}

